# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18y6UYAsZe9AvtW1_szKBonbzV4-BOsap
"""

import numpy as np
import pandas as pd
from sklearn import tree

irisDataset = pd.read_csv('Dataset Iris.csv',delimiter=';',header =0)

irisDataset.head()

irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

print(irisDataset)

irisDataset = irisDataset.drop(labels='id',axis=1)

print(irisDataset)

irisDataset = irisDataset.to_numpy()

print(irisDataset)

dataTraining = np.concatenate((irisDataset[0:40, ;], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, ;], irisDataset[90:100, :]),
                              axis=0)

print(dataTraining)
len(dataTraining)

inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTesting)
len(labelTraining)

model = tree.DecisionClassfier()

model = model.fit(inputTraining
                  , labelTraining)

hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya", labelTesting)
print("Hasil Prediksi ; ", hasilprediksi)

prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi Benar :",prediksiBenar,"data")
print("prediksi Salah :",prediksiSalah,"data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100,"%")